spring :
  profiles :
    active : def
    
---
spring:
   profiles: def
eureka:
  instance:
    hostname: localhost:8082
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
     defaultZone: http://localhost:7001/discovery-service/eureka/